// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEewOsmhasZsa3C-MJ4GkOf-VpFcKh0Gw',
    appId: '1:599514547596:web:698b0911dc7befb21042a9',
    messagingSenderId: '599514547596',
    projectId: 'endless-orb-206506',
    authDomain: 'endless-orb-206506.firebaseapp.com',
    storageBucket: 'endless-orb-206506.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxgT5ApBVF5bZ6QzM_ehDJx-q2g3L930Q',
    appId: '1:599514547596:android:6d60ae2d0e31b86b1042a9',
    messagingSenderId: '599514547596',
    projectId: 'endless-orb-206506',
    storageBucket: 'endless-orb-206506.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1A9uZow2Ox3SpW277PPrycHkQPsDnRTc',
    appId: '1:599514547596:ios:6d56e6e328cfff271042a9',
    messagingSenderId: '599514547596',
    projectId: 'endless-orb-206506',
    storageBucket: 'endless-orb-206506.appspot.com',
    iosBundleId: 'com.dicoding.a199FlutterExpertProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1A9uZow2Ox3SpW277PPrycHkQPsDnRTc',
    appId: '1:599514547596:ios:c9603e8969f0e7641042a9',
    messagingSenderId: '599514547596',
    projectId: 'endless-orb-206506',
    storageBucket: 'endless-orb-206506.appspot.com',
    iosBundleId: 'com.dicoding.a199FlutterExpertProject.RunnerTests',
  );
}
