// Mocks generated by Mockito 5.4.2 from annotations
// in ditonton/test/presentation/pages/tv_series_detail_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i13;
import 'dart:ui' as _i14;

import 'package:core/core.dart' as _i10;
import 'package:core/domain/entities/season.dart' as _i12;
import 'package:core/domain/entities/tv_series.dart' as _i11;
import 'package:core/domain/entities/tv_series_detail.dart' as _i8;
import 'package:core/domain/usecases/get_tv_series_detail.dart' as _i2;
import 'package:core/domain/usecases/get_tv_series_recommendations.dart' as _i3;
import 'package:core/domain/usecases/get_tv_series_seasons.dart' as _i4;
import 'package:core/domain/usecases/get_tv_series_watchist_status.dart' as _i5;
import 'package:core/domain/usecases/remove_tv_series_watchlist.dart' as _i7;
import 'package:core/domain/usecases/save_tv_series_watchlist.dart' as _i6;
import 'package:core/presentation/provider/tv_series_detail_notifier.dart'
    as _i9;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetTvSeriesDetail_0 extends _i1.SmartFake
    implements _i2.GetTvSeriesDetail {
  _FakeGetTvSeriesDetail_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetTvSeriesRecommendation_1 extends _i1.SmartFake
    implements _i3.GetTvSeriesRecommendation {
  _FakeGetTvSeriesRecommendation_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetTvSeriesSeason_2 extends _i1.SmartFake
    implements _i4.GetTvSeriesSeason {
  _FakeGetTvSeriesSeason_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetTvSeriesWatchListStatus_3 extends _i1.SmartFake
    implements _i5.GetTvSeriesWatchListStatus {
  _FakeGetTvSeriesWatchListStatus_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTvSeriesSaveWatchList_4 extends _i1.SmartFake
    implements _i6.TvSeriesSaveWatchList {
  _FakeTvSeriesSaveWatchList_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTvSeriesRemoveWatchlist_5 extends _i1.SmartFake
    implements _i7.TvSeriesRemoveWatchlist {
  _FakeTvSeriesRemoveWatchlist_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTvSeriesDetail_6 extends _i1.SmartFake
    implements _i8.TvSeriesDetail {
  _FakeTvSeriesDetail_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TvSeriesDetailNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesDetailNotifier extends _i1.Mock
    implements _i9.TvSeriesDetailNotifier {
  MockTvSeriesDetailNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetTvSeriesDetail get getTvSeriesDetail => (super.noSuchMethod(
        Invocation.getter(#getTvSeriesDetail),
        returnValue: _FakeGetTvSeriesDetail_0(
          this,
          Invocation.getter(#getTvSeriesDetail),
        ),
      ) as _i2.GetTvSeriesDetail);
  @override
  _i3.GetTvSeriesRecommendation get getTvSeriesRecommendation =>
      (super.noSuchMethod(
        Invocation.getter(#getTvSeriesRecommendation),
        returnValue: _FakeGetTvSeriesRecommendation_1(
          this,
          Invocation.getter(#getTvSeriesRecommendation),
        ),
      ) as _i3.GetTvSeriesRecommendation);
  @override
  _i4.GetTvSeriesSeason get getTvSeriesSeason => (super.noSuchMethod(
        Invocation.getter(#getTvSeriesSeason),
        returnValue: _FakeGetTvSeriesSeason_2(
          this,
          Invocation.getter(#getTvSeriesSeason),
        ),
      ) as _i4.GetTvSeriesSeason);
  @override
  _i5.GetTvSeriesWatchListStatus get getTvSeriesWatchListStatus =>
      (super.noSuchMethod(
        Invocation.getter(#getTvSeriesWatchListStatus),
        returnValue: _FakeGetTvSeriesWatchListStatus_3(
          this,
          Invocation.getter(#getTvSeriesWatchListStatus),
        ),
      ) as _i5.GetTvSeriesWatchListStatus);
  @override
  _i6.TvSeriesSaveWatchList get tvSeriesSaveWatchList => (super.noSuchMethod(
        Invocation.getter(#tvSeriesSaveWatchList),
        returnValue: _FakeTvSeriesSaveWatchList_4(
          this,
          Invocation.getter(#tvSeriesSaveWatchList),
        ),
      ) as _i6.TvSeriesSaveWatchList);
  @override
  _i7.TvSeriesRemoveWatchlist get tvSeriesRemoveWatchlist =>
      (super.noSuchMethod(
        Invocation.getter(#tvSeriesRemoveWatchlist),
        returnValue: _FakeTvSeriesRemoveWatchlist_5(
          this,
          Invocation.getter(#tvSeriesRemoveWatchlist),
        ),
      ) as _i7.TvSeriesRemoveWatchlist);
  @override
  _i10.RequestState get tvSeriesDetailState => (super.noSuchMethod(
        Invocation.getter(#tvSeriesDetailState),
        returnValue: _i10.RequestState.isEmpty,
      ) as _i10.RequestState);
  @override
  _i8.TvSeriesDetail get tvSeriesDetail => (super.noSuchMethod(
        Invocation.getter(#tvSeriesDetail),
        returnValue: _FakeTvSeriesDetail_6(
          this,
          Invocation.getter(#tvSeriesDetail),
        ),
      ) as _i8.TvSeriesDetail);
  @override
  _i10.RequestState get getTvSeriesRecommendationState => (super.noSuchMethod(
        Invocation.getter(#getTvSeriesRecommendationState),
        returnValue: _i10.RequestState.isEmpty,
      ) as _i10.RequestState);
  @override
  List<_i11.TvSeries> get tvSeriesRecommendations => (super.noSuchMethod(
        Invocation.getter(#tvSeriesRecommendations),
        returnValue: <_i11.TvSeries>[],
      ) as List<_i11.TvSeries>);
  @override
  _i10.RequestState get getTvSeriesSeasonsState => (super.noSuchMethod(
        Invocation.getter(#getTvSeriesSeasonsState),
        returnValue: _i10.RequestState.isEmpty,
      ) as _i10.RequestState);
  @override
  List<_i12.Season> get tvSeriesSeasons => (super.noSuchMethod(
        Invocation.getter(#tvSeriesSeasons),
        returnValue: <_i12.Season>[],
      ) as List<_i12.Season>);
  @override
  String get message => (super.noSuchMethod(
        Invocation.getter(#message),
        returnValue: '',
      ) as String);
  @override
  bool get isAddedToWatchlist => (super.noSuchMethod(
        Invocation.getter(#isAddedToWatchlist),
        returnValue: false,
      ) as bool);
  @override
  String get watchlistMessage => (super.noSuchMethod(
        Invocation.getter(#watchlistMessage),
        returnValue: '',
      ) as String);
  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);
  @override
  _i13.Future<void> fetchTvSeriesDetail({required int? id}) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchTvSeriesDetail,
          [],
          {#id: id},
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);
  @override
  _i13.Future<void> addWatchlist(_i8.TvSeriesDetail? tvSeriesDetail) =>
      (super.noSuchMethod(
        Invocation.method(
          #addWatchlist,
          [tvSeriesDetail],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);
  @override
  _i13.Future<void> removeFromWatchlist(_i8.TvSeriesDetail? tvSeriesDetail) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFromWatchlist,
          [tvSeriesDetail],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);
  @override
  _i13.Future<void> loadWatchlistStatus(int? id) => (super.noSuchMethod(
        Invocation.method(
          #loadWatchlistStatus,
          [id],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);
  @override
  void addListener(_i14.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void removeListener(_i14.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
