// Mocks generated by Mockito 5.4.2 from annotations
// in ditonton/test/presentation/pages/tv_series_detail_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i11;
import 'dart:ui' as _i12;

import 'package:ditonton/common/state_enum.dart' as _i9;
import 'package:ditonton/domain/entities/tv_series.dart' as _i10;
import 'package:ditonton/domain/entities/tv_series_detail.dart' as _i7;
import 'package:ditonton/domain/usecases/get_tv_series_detail.dart' as _i2;
import 'package:ditonton/domain/usecases/get_tv_series_recommendations.dart'
    as _i3;
import 'package:ditonton/domain/usecases/get_tv_series_watchist_status.dart'
    as _i4;
import 'package:ditonton/domain/usecases/remove_tv_series_watchlist.dart'
    as _i6;
import 'package:ditonton/domain/usecases/save_tv_series_watchlist.dart' as _i5;
import 'package:ditonton/presentation/provider/tv_series_detail_notifier.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetTvSeriesDetail_0 extends _i1.SmartFake
    implements _i2.GetTvSeriesDetail {
  _FakeGetTvSeriesDetail_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetTvSeriesRecommendation_1 extends _i1.SmartFake
    implements _i3.GetTvSeriesRecommendation {
  _FakeGetTvSeriesRecommendation_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetTvSeriesWatchListStatus_2 extends _i1.SmartFake
    implements _i4.GetTvSeriesWatchListStatus {
  _FakeGetTvSeriesWatchListStatus_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTvSeriesSaveWatchList_3 extends _i1.SmartFake
    implements _i5.TvSeriesSaveWatchList {
  _FakeTvSeriesSaveWatchList_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTvSeriesRemoveWatchlist_4 extends _i1.SmartFake
    implements _i6.TvSeriesRemoveWatchlist {
  _FakeTvSeriesRemoveWatchlist_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTvSeriesDetail_5 extends _i1.SmartFake
    implements _i7.TvSeriesDetail {
  _FakeTvSeriesDetail_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TvSeriesDetailNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesDetailNotifier extends _i1.Mock
    implements _i8.TvSeriesDetailNotifier {
  MockTvSeriesDetailNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetTvSeriesDetail get getTvSeriesDetail => (super.noSuchMethod(
        Invocation.getter(#getTvSeriesDetail),
        returnValue: _FakeGetTvSeriesDetail_0(
          this,
          Invocation.getter(#getTvSeriesDetail),
        ),
      ) as _i2.GetTvSeriesDetail);
  @override
  _i3.GetTvSeriesRecommendation get getTvSeriesRecommendation =>
      (super.noSuchMethod(
        Invocation.getter(#getTvSeriesRecommendation),
        returnValue: _FakeGetTvSeriesRecommendation_1(
          this,
          Invocation.getter(#getTvSeriesRecommendation),
        ),
      ) as _i3.GetTvSeriesRecommendation);
  @override
  _i4.GetTvSeriesWatchListStatus get getTvSeriesWatchListStatus =>
      (super.noSuchMethod(
        Invocation.getter(#getTvSeriesWatchListStatus),
        returnValue: _FakeGetTvSeriesWatchListStatus_2(
          this,
          Invocation.getter(#getTvSeriesWatchListStatus),
        ),
      ) as _i4.GetTvSeriesWatchListStatus);
  @override
  _i5.TvSeriesSaveWatchList get tvSeriesSaveWatchList => (super.noSuchMethod(
        Invocation.getter(#tvSeriesSaveWatchList),
        returnValue: _FakeTvSeriesSaveWatchList_3(
          this,
          Invocation.getter(#tvSeriesSaveWatchList),
        ),
      ) as _i5.TvSeriesSaveWatchList);
  @override
  _i6.TvSeriesRemoveWatchlist get tvSeriesRemoveWatchlist =>
      (super.noSuchMethod(
        Invocation.getter(#tvSeriesRemoveWatchlist),
        returnValue: _FakeTvSeriesRemoveWatchlist_4(
          this,
          Invocation.getter(#tvSeriesRemoveWatchlist),
        ),
      ) as _i6.TvSeriesRemoveWatchlist);
  @override
  _i9.RequestState get tvSeriesDetailState => (super.noSuchMethod(
        Invocation.getter(#tvSeriesDetailState),
        returnValue: _i9.RequestState.Empty,
      ) as _i9.RequestState);
  @override
  _i7.TvSeriesDetail get tvSeriesDetail => (super.noSuchMethod(
        Invocation.getter(#tvSeriesDetail),
        returnValue: _FakeTvSeriesDetail_5(
          this,
          Invocation.getter(#tvSeriesDetail),
        ),
      ) as _i7.TvSeriesDetail);
  @override
  _i9.RequestState get getTvSeriesRecommendationState => (super.noSuchMethod(
        Invocation.getter(#getTvSeriesRecommendationState),
        returnValue: _i9.RequestState.Empty,
      ) as _i9.RequestState);
  @override
  List<_i10.TvSeries> get tvSeriesRecommendations => (super.noSuchMethod(
        Invocation.getter(#tvSeriesRecommendations),
        returnValue: <_i10.TvSeries>[],
      ) as List<_i10.TvSeries>);
  @override
  String get message => (super.noSuchMethod(
        Invocation.getter(#message),
        returnValue: '',
      ) as String);
  @override
  bool get isAddedToWatchlist => (super.noSuchMethod(
        Invocation.getter(#isAddedToWatchlist),
        returnValue: false,
      ) as bool);
  @override
  String get watchlistMessage => (super.noSuchMethod(
        Invocation.getter(#watchlistMessage),
        returnValue: '',
      ) as String);
  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);
  @override
  _i11.Future<void> fetchDetailTvSeries({required int? id}) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchDetailTvSeries,
          [],
          {#id: id},
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  _i11.Future<void> addWatchlist(_i7.TvSeriesDetail? tvSeriesDetail) =>
      (super.noSuchMethod(
        Invocation.method(
          #addWatchlist,
          [tvSeriesDetail],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  _i11.Future<void> removeFromWatchlist(_i7.TvSeriesDetail? tvSeriesDetail) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFromWatchlist,
          [tvSeriesDetail],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  _i11.Future<void> loadWatchlistStatus(int? id) => (super.noSuchMethod(
        Invocation.method(
          #loadWatchlistStatus,
          [id],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  void addListener(_i12.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void removeListener(_i12.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
